global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-api:8082']

  - job_name: 'order-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-api:8083']

  - job_name: 'user-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-api:8084']