server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-api
          uri: http://product-api:8082
          predicates:
            - Path=/products/**
        - id: order-api
          uri: http://order-api:8083
          predicates:
            - Path=/orders/**
        - id: user-api
          uri: http://user-api:8084
          predicates:
            - Path=/users/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
